name: Docker Images Publish

on:
  push:
    branches: [main]

jobs:

  create_redis_image:

    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2
    - name: Get the version
      id: vars
      run: echo "::set-output name=tag::$(git rev-parse --short HEAD)"
    - uses: docker/setup-buildx-action@v1
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Push redis image to docker hub
      uses: docker/build-push-action@v2
      with:
        context: . 
        tags: |
          adimus11/test-redis-repo:${{steps.vars.outputs.tag}}
          adimus11/test-redis-repo:latest
        push: true
        file: ./redis/Dockerfile 
    - name: Push golang image to docker hub
      uses: docker/build-push-action@v2
      with:
        context: .
        tags: |
          adimus11/test-golang-repo:${{steps.vars.outputs.tag}}
          adimus11/test-golang-repo:latest
        push: true
        file: ./golang/Dockerfile
        
  create_golang_image:

    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2
    - name: Get the version
      id: vars
      run: echo "::set-output name=tag::$(git rev-parse --short HEAD)"
    - uses: docker/setup-buildx-action@v1
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Push golang image to docker hub
      uses: docker/build-push-action@v2
      with:
        context: .
        tags: |
          adimus11/test-golang-repo:${{steps.vars.outputs.tag}}
          adimus11/test-golang-repo:latest
        push: true
        file: ./golang/Dockerfile
