name: Docker Images Publish

on:
  push:
    branches: [main]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2
    - name: Push redis image to docker hub
      uses: docker/build-push-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: adimus11/test-redis-repo
        tag_with_ref: true
        file: ./redis/Dockerfile 
    - name: Push golang image to docker hub
      uses: docker/build-push-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: adimus11/test-golang-repo
        tag_with_ref: true
        file: ./golang/Dockerfile
